# Generated by Django 5.2.2 on 2025-06-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Склад', max_length=50)),
                ('volume', models.FloatField()),
                ('sio2_pct', models.FloatField()),
                ('fe_pct', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('max_capacity', models.FloatField()),
                ('current_weight', models.FloatField()),
                ('sio2_pct', models.FloatField()),
                ('fe_pct', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UnloadPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.truck')),
            ],
        ),
    ]
